<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <RootNamespace>ImageStorageHelper</RootNamespace>
    <AssemblyName>ImageStorageHelper</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="imagestorageservicemanaged">
      <HintPath>imagestorageservicemanaged.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="imagecommon">
      <HintPath>imagecommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="toolscommon">
      <HintPath>toolscommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
