
#pragma once

#define IDS_APP_TITLE        100
#define IDS_LBL_WSK          101
#define IDS_BTN_BROWSE       102
#define IDS_BTN_DETECT       103
#define IDS_LBL_WORKSPACE    104
#define IDS_BTN_SELECT       105
#define IDS_LBL_ARCH         106
#define IDS_LBL_PRODUCT      107
#define IDS_RADIO_PHYS       108
#define IDS_RADIO_VM         109
#define IDS_BTN_BUILD        110
#define IDS_LBL_OUTPUT       111
#define IDS_STATUS_READY     112
#define IDS_MSG_SEL_WSK      113
#define IDS_MSG_SEL_WS       114
#define IDS_MSG_SEL_ARCH     115
#define IDS_MSG_SEL_PROD     116
#define IDS_MSG_WSK_INVALID  117
#define IDS_MSG_WS_NOTDIR    118
#define IDS_MSG_WS_CREATE    119
#define IDS_MSG_ARM_WARN     120
#define IDS_MSG_ARM_TITLE    121
#define IDS_STATUS_BUILDING  122
#define IDS_STATUS_SUCCESS    123
#define IDS_STATUS_FAIL       124
#define IDS_MSG_SUCCESS       125
#define IDS_MSG_DONE          126
#define IDS_MSG_FAIL          127
#define IDS_MSG_FAILTITLE     128
#define IDS_OUT_HEADER        129
#define IDS_OUT_DETECT_OK     130
#define IDS_OUT_DETECT_NO     131
#define IDS_OUT_XML_TITLE     132
#define IDS_OUT_XML_SEL       133
#define IDS_OUT_XML_NONE      134
#define IDS_OUT_BUILD_START   135
#define IDS_OUT_BUILD_SUCCESS 136
#define IDS_OUT_BUILD_FAIL    137
#define IDS_OUT_EXITCODE      138
#define IDS_OUT_OUTPUT_DIR    139
#define IDS_MSG_RUNNING       140
#define IDS_MENU_LANG         141
#define IDS_MENU_SWITCH       142
#define IDS_MENU_HELP         143
#define IDS_MENU_ABOUT        144
