using System.Collections.Generic;

namespace VirtualDiskExplorer;

public static class Lang
{
    public static string Current { get; private set; } = "zh-cn";

    static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["zh-cn"] = new()
        {
            ["AppTitle"] = "虚拟磁盘浏览器",
            ["FileMenu"] = "文件(&F)",
            ["OpenDisk"] = "打开磁盘...",
            ["Exit"] = "退出",
            ["LanguageMenu"] = "语言(&L)",
            ["HelpMenu"] = "帮助(&H)",
            ["About"] = "关于",
            ["OpenBtn"] = "打开",
            ["BackBtn"] = "后退",
            ["ForwardBtn"] = "前进",
            ["UpBtn"] = "上级",
            ["PathLabel"] = "路径:",
            ["ColName"] = "名称",
            ["ColSize"] = "大小",
            ["ColType"] = "类型",
            ["ColModified"] = "修改时间",
            ["Disk"] = "磁盘",
            ["Partition"] = "分区",
            ["RawFs"] = "原始文件系统",
            ["OpenDiskTitle"] = "选择虚拟磁盘文件",
            ["OpenDiskFilter"] = "虚拟磁盘文件 (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|所有文件 (*.*)|*.*",
            ["ErrorOpenDisk"] = "打开磁盘失败: ",
            ["ErrorOpenPartition"] = "打开分区失败: ",
            ["ErrorOpenFile"] = "打开文件失败: ",
            ["NoFilesystem"] = "(无法识别的文件系统)",
            ["EmptyFolder"] = "(空文件夹)",
            ["Folder"] = "文件夹",
            ["File"] = "文件",
            ["SPACEDB"] = "Windows 存储池 (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "版本: ",
            ["SPACEDBPoolId"] = "池 ID: ",
            ["SPACEDBSize"] = "池大小: ",
            ["SPACEDBVirtualDisks"] = "虚拟磁盘",
            ["SPACEDBNote"] = "[提示] SPACEDB 使用块分配；数据可能不连续。完整浏览需要转换。",
            ["StoragePool"] = "存储池",
            ["Info"] = "信息",
            ["VirtualDisk"] = "虚拟磁盘",
            ["DoubleClickBrowse"] = "双击浏览",
            ["SPACEDBLocationNotFound"] = "虚拟磁盘位置未检测到。\n\n是否尝试完整提取作为回退？",
            ["SPACEDBOpenTitle"] = "SPACEDB 虚拟磁盘",
            ["SPACEDBOpenPrompt"] = "打开虚拟磁盘 '{0}' ({1:F2} GB)?\n\n是 = 直接读取 (无临时文件，推荐)\n否 = 提取转换 (完整读取，需要磁盘空间)\n取消 = 不操作",
            ["DirectReadFailed"] = "直接读取失败。尝试提取作为回退？",
            ["DirectReadError"] = "直接读取错误: ",
            ["Extracting"] = "正在提取虚拟磁盘... ({0}) - 可能需要一些时间",
            ["ExtractionFailed"] = "提取虚拟磁盘失败。",
            ["OpenExtractedFailed"] = "无法打开提取的虚拟磁盘。",
            ["OpeningDirect"] = "正在打开虚拟磁盘 (直接读取)... ({0})",
            ["NestedDiskLabel"] = "[嵌套/存储池] {0} [{1}] {2:F2} GB",
            ["DirectReadLabel"] = "(直接读取)",
            ["ExtractedLabel"] = "(已提取)",
            ["AboutTitle"] = "关于",
            ["AboutText"] = "虚拟磁盘浏览器\n版本 1.0\n\n支持 VHD/VHDX/VMDK/VDI/QCOW2/RAW 格式\n支持 NTFS/FAT 文件系统\n支持 Windows 存储池 (SPACEDB/OSPool)\n\n组织: WinStory 2026\nhttps://wiki.win-story.cn\n编译者: DF4D3110",
            ["LangSelectTitle"] = "选择语言",
            ["LangSelectPrompt"] = "请选择界面语言:",
            ["UnknownLang"] = "未知语言代码，使用默认 zh-cn。支持: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
        ["zh-tw"] = new()
        {
            ["AppTitle"] = "虛擬磁碟瀏覽器",
            ["FileMenu"] = "檔案(&F)",
            ["OpenDisk"] = "開啟磁碟...",
            ["Exit"] = "退出",
            ["LanguageMenu"] = "語言(&L)",
            ["HelpMenu"] = "說明(&H)",
            ["About"] = "關於",
            ["OpenBtn"] = "開啟",
            ["BackBtn"] = "後退",
            ["ForwardBtn"] = "前進",
            ["UpBtn"] = "上級",
            ["PathLabel"] = "路徑:",
            ["ColName"] = "名稱",
            ["ColSize"] = "大小",
            ["ColType"] = "類型",
            ["ColModified"] = "修改時間",
            ["Disk"] = "磁碟",
            ["Partition"] = "分割區",
            ["RawFs"] = "原始檔案系統",
            ["OpenDiskTitle"] = "選擇虛擬磁碟檔案",
            ["OpenDiskFilter"] = "虛擬磁碟檔案 (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|所有檔案 (*.*)|*.*",
            ["ErrorOpenDisk"] = "開啟磁碟失敗: ",
            ["ErrorOpenPartition"] = "開啟分割區失敗: ",
            ["ErrorOpenFile"] = "開啟檔案失敗: ",
            ["NoFilesystem"] = "(無法辨識的檔案系統)",
            ["EmptyFolder"] = "(空資料夾)",
            ["Folder"] = "資料夾",
            ["File"] = "檔案",
            ["SPACEDB"] = "Windows 儲存池 (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "版本: ",
            ["SPACEDBPoolId"] = "集區 ID: ",
            ["SPACEDBSize"] = "集區大小: ",
            ["SPACEDBVirtualDisks"] = "虛擬磁碟",
            ["SPACEDBNote"] = "[提示] SPACEDB 使用區塊配置；資料可能不連續。完整瀏覽需要轉換。",
            ["StoragePool"] = "儲存池",
            ["Info"] = "資訊",
            ["VirtualDisk"] = "虛擬磁碟",
            ["DoubleClickBrowse"] = "雙擊瀏覽",
            ["SPACEDBLocationNotFound"] = "虛擬磁碟位置未偵測到。\n\n是否嘗試完整擷取作為後退？",
            ["SPACEDBOpenTitle"] = "SPACEDB 虛擬磁碟",
            ["SPACEDBOpenPrompt"] = "開啟虛擬磁碟 '{0}' ({1:F2} GB)?\n\n是 = 直接讀取 (無暫存檔，推薦)\n否 = 擷取轉換 (完整讀取，需要磁碟空間)\n取消 = 不操作",
            ["DirectReadFailed"] = "直接讀取失敗。嘗試擷取作為後退？",
            ["DirectReadError"] = "直接讀取錯誤: ",
            ["Extracting"] = "正在擷取虛擬磁碟... ({0}) - 可能需要一些時間",
            ["ExtractionFailed"] = "擷取虛擬磁碟失敗。",
            ["OpenExtractedFailed"] = "無法開啟擷取的虛擬磁碟。",
            ["OpeningDirect"] = "正在開啟虛擬磁碟 (直接讀取)... ({0})",
            ["NestedDiskLabel"] = "[巢狀/儲存池] {0} [{1}] {2:F2} GB",
            ["DirectReadLabel"] = "(直接讀取)",
            ["ExtractedLabel"] = "(已擷取)",
            ["AboutTitle"] = "關於",
            ["AboutText"] = "虛擬磁碟瀏覽器\n版本 1.0\n\n支援 VHD/VHDX/VMDK/VDI/QCOW2/RAW 格式\n支援 NTFS/FAT 檔案系統\n支援 Windows 儲存池 (SPACEDB/OSPool)\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\n編譯者: DF4D3110",
            ["LangSelectTitle"] = "選擇語言",
            ["LangSelectPrompt"] = "請選擇介面語言:",
            ["UnknownLang"] = "未知語言代碼，使用預設 zh-cn。支援: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
        ["en-us"] = new()
        {
            ["AppTitle"] = "Virtual Disk Explorer",
            ["FileMenu"] = "&File",
            ["OpenDisk"] = "&Open Disk...",
            ["Exit"] = "E&xit",
            ["LanguageMenu"] = "&Language",
            ["HelpMenu"] = "&Help",
            ["About"] = "&About",
            ["OpenBtn"] = "Open",
            ["BackBtn"] = "Back",
            ["ForwardBtn"] = "Forward",
            ["UpBtn"] = "Up",
            ["PathLabel"] = "Path:",
            ["ColName"] = "Name",
            ["ColSize"] = "Size",
            ["ColType"] = "Type",
            ["ColModified"] = "Modified",
            ["Disk"] = "Disk",
            ["Partition"] = "Partition",
            ["RawFs"] = "Raw filesystem",
            ["OpenDiskTitle"] = "Select Virtual Disk File",
            ["OpenDiskFilter"] = "Virtual Disk Files (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|All Files (*.*)|*.*",
            ["ErrorOpenDisk"] = "Failed to open disk: ",
            ["ErrorOpenPartition"] = "Failed to open partition: ",
            ["ErrorOpenFile"] = "Failed to open file: ",
            ["NoFilesystem"] = "(unrecognized filesystem)",
            ["EmptyFolder"] = "(empty folder)",
            ["Folder"] = "Folder",
            ["File"] = "File",
            ["SPACEDB"] = "Windows Storage Spaces (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "Version: ",
            ["SPACEDBPoolId"] = "Pool ID: ",
            ["SPACEDBSize"] = "Pool Size: ",
            ["SPACEDBVirtualDisks"] = "Virtual Disks",
            ["SPACEDBNote"] = "[Note] SPACEDB uses block allocation; data may be non-contiguous. Full browse requires conversion.",
            ["StoragePool"] = "Storage Pool",
            ["Info"] = "Info",
            ["VirtualDisk"] = "Virtual Disk",
            ["DoubleClickBrowse"] = "Double-click to browse",
            ["SPACEDBLocationNotFound"] = "Virtual disk location not detected.\n\nWould you like to try full extraction as fallback?",
            ["SPACEDBOpenTitle"] = "SPACEDB Virtual Disk",
            ["SPACEDBOpenPrompt"] = "Open virtual disk '{0}' ({1:F2} GB)?\n\nYes = Direct read (no temp files, recommended)\nNo = Extract & convert (full read, requires disk space)\nCancel = Do nothing",
            ["DirectReadFailed"] = "Direct read failed. Try extraction as fallback?",
            ["DirectReadError"] = "Direct read error: ",
            ["Extracting"] = "Extracting virtual disk... ({0}) - this may take a while",
            ["ExtractionFailed"] = "Failed to extract virtual disk.",
            ["OpenExtractedFailed"] = "Failed to open extracted virtual disk.",
            ["OpeningDirect"] = "Opening virtual disk (direct read)... ({0})",
            ["NestedDiskLabel"] = "[Nested/StoragePool] {0} [{1}] {2:F2} GB",
            ["DirectReadLabel"] = "(direct read)",
            ["ExtractedLabel"] = "(extracted)",
            ["AboutTitle"] = "About",
            ["AboutText"] = "Virtual Disk Explorer\nVersion 1.0\n\nSupports VHD/VHDX/VMDK/VDI/QCOW2/RAW formats\nSupports NTFS/FAT filesystems\nSupports Windows Storage Spaces (SPACEDB/OSPool)\n\nOrganization: WinStory 2026\nhttps://wiki.win-story.cn\nCompiled by: DF4D3110",
            ["LangSelectTitle"] = "Select Language",
            ["LangSelectPrompt"] = "Please select interface language:",
            ["UnknownLang"] = "Unknown language code, using default zh-cn. Supported: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
        ["ja-jp"] = new()
        {
            ["AppTitle"] = "仮想ディスクブラウザ",
            ["FileMenu"] = "ファイル(&F)",
            ["OpenDisk"] = "ディスクを開く...",
            ["Exit"] = "終了",
            ["LanguageMenu"] = "言語(&L)",
            ["HelpMenu"] = "ヘルプ(&H)",
            ["About"] = "バージョン情報",
            ["OpenBtn"] = "開く",
            ["BackBtn"] = "戻る",
            ["ForwardBtn"] = "進む",
            ["UpBtn"] = "上へ",
            ["PathLabel"] = "パス:",
            ["ColName"] = "名前",
            ["ColSize"] = "サイズ",
            ["ColType"] = "種類",
            ["ColModified"] = "更新日時",
            ["Disk"] = "ディスク",
            ["Partition"] = "パーティション",
            ["RawFs"] = "raw ファイルシステム",
            ["OpenDiskTitle"] = "仮想ディスクファイルを選択",
            ["OpenDiskFilter"] = "仮想ディスクファイル (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|すべてのファイル (*.*)|*.*",
            ["ErrorOpenDisk"] = "ディスクを開けません: ",
            ["ErrorOpenPartition"] = "パーティションを開けません: ",
            ["ErrorOpenFile"] = "ファイルを開けません: ",
            ["NoFilesystem"] = "(認識できないファイルシステム)",
            ["EmptyFolder"] = "(空のフォルダ)",
            ["Folder"] = "フォルダ",
            ["File"] = "ファイル",
            ["SPACEDB"] = "Windows 記憶域スペース (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "バージョン: ",
            ["SPACEDBPoolId"] = "プール ID: ",
            ["SPACEDBSize"] = "プール サイズ: ",
            ["SPACEDBVirtualDisks"] = "仮想ディスク",
            ["SPACEDBNote"] = "[注意] SPACEDB はブロック割り当てを使用；データが不連続な場合があります。完全な閲覧には変換が必要です。",
            ["StoragePool"] = "記憶域プール",
            ["Info"] = "情報",
            ["VirtualDisk"] = "仮想ディスク",
            ["DoubleClickBrowse"] = "ダブルクリックで閲覧",
            ["SPACEDBLocationNotFound"] = "仮想ディスクの場所が検出されませんでした。\n\nフォールバックとして完全抽出を試みますか？",
            ["SPACEDBOpenTitle"] = "SPACEDB 仮想ディスク",
            ["SPACEDBOpenPrompt"] = "仮想ディスク '{0}' ({1:F2} GB) を開きますか？\n\nはい = 直接読み取り (一時ファイルなし、推奨)\nいいえ = 抽出と変換 (完全読み取り、ディスク容量が必要)\nキャンセル = 何もしない",
            ["DirectReadFailed"] = "直接読み取りに失敗しました。フォールバックとして抽出を試みますか？",
            ["DirectReadError"] = "直接読み取りエラー: ",
            ["Extracting"] = "仮想ディスクを抽出中... ({0}) - 時間がかかる場合があります",
            ["ExtractionFailed"] = "仮想ディスクの抽出に失敗しました。",
            ["OpenExtractedFailed"] = "抽出された仮想ディスクを開けません。",
            ["OpeningDirect"] = "仮想ディスクを開いています (直接読み取り)... ({0})",
            ["NestedDiskLabel"] = "[ネスト/記憶域プール] {0} [{1}] {2:F2} GB",
            ["DirectReadLabel"] = "(直接読み取り)",
            ["ExtractedLabel"] = "(抽出済み)",
            ["AboutTitle"] = "バージョン情報",
            ["AboutText"] = "仮想ディスクブラウザ\nバージョン 1.0\n\nVHD/VHDX/VMDK/VDI/QCOW2/RAW 形式をサポート\nNTFS/FAT ファイルシステムをサポート\nWindows 記憶域スペース (SPACEDB/OSPool) をサポート\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\nコンパイル: DF4D3110",
            ["LangSelectTitle"] = "言語を選択",
            ["LangSelectPrompt"] = "インターフェース言語を選択してください:",
            ["UnknownLang"] = "不明な言語コード、デフォルト zh-cn を使用。サポート: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
        ["ru-ru"] = new()
        {
            ["AppTitle"] = "Просмотрщик виртуальных дисков",
            ["FileMenu"] = "Файл(&F)",
            ["OpenDisk"] = "Открыть диск...",
            ["Exit"] = "Выход",
            ["LanguageMenu"] = "Язык(&L)",
            ["HelpMenu"] = "Справка(&H)",
            ["About"] = "О программе",
            ["OpenBtn"] = "Открыть",
            ["BackBtn"] = "Назад",
            ["ForwardBtn"] = "Вперёд",
            ["UpBtn"] = "Вверх",
            ["PathLabel"] = "Путь:",
            ["ColName"] = "Имя",
            ["ColSize"] = "Размер",
            ["ColType"] = "Тип",
            ["ColModified"] = "Изменён",
            ["Disk"] = "Диск",
            ["Partition"] = "Раздел",
            ["RawFs"] = "сырая файловая система",
            ["OpenDiskTitle"] = "Выберите файл виртуального диска",
            ["OpenDiskFilter"] = "Файлы виртуальных дисков (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|Все файлы (*.*)|*.*",
            ["ErrorOpenDisk"] = "Не удалось открыть диск: ",
            ["ErrorOpenPartition"] = "Не удалось открыть раздел: ",
            ["ErrorOpenFile"] = "Не удалось открыть файл: ",
            ["NoFilesystem"] = "(нераспознанная файловая система)",
            ["EmptyFolder"] = "(пустая папка)",
            ["Folder"] = "Папка",
            ["File"] = "Файл",
            ["SPACEDB"] = "Пространства хранения Windows (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "Версия: ",
            ["SPACEDBPoolId"] = "ID пула: ",
            ["SPACEDBSize"] = "Размер пула: ",
            ["SPACEDBVirtualDisks"] = "Виртуальные диски",
            ["SPACEDBNote"] = "[Примечание] SPACEDB использует блочное выделение; данные могут быть несмежными. Для полного просмотра требуется преобразование.",
            ["StoragePool"] = "Пул хранения",
            ["Info"] = "Инфо",
            ["VirtualDisk"] = "Виртуальный диск",
            ["DoubleClickBrowse"] = "Двойной клик для просмотра",
            ["SPACEDBLocationNotFound"] = "Расположение виртуального диска не обнаружено.\n\nПопробовать полное извлечение в качестве запасного варианта?",
            ["SPACEDBOpenTitle"] = "Виртуальный диск SPACEDB",
            ["SPACEDBOpenPrompt"] = "Открыть виртуальный диск '{0}' ({1:F2} ГБ)?\n\nДа = Прямое чтение (без временных файлов, рекомендуется)\nНет = Извлечь и преобразовать (полное чтение, требуется место на диске)\nОтмена = Ничего не делать",
            ["DirectReadFailed"] = "Прямое чтение не удалось. Попробовать извлечение в качестве запасного варианта?",
            ["DirectReadError"] = "Ошибка прямого чтения: ",
            ["Extracting"] = "Извлечение виртуального диска... ({0}) - это может занять некоторое время",
            ["ExtractionFailed"] = "Не удалось извлечь виртуальный диск.",
            ["OpenExtractedFailed"] = "Не удалось открыть извлечённый виртуальный диск.",
            ["OpeningDirect"] = "Открытие виртуального диска (прямое чтение)... ({0})",
            ["NestedDiskLabel"] = "[Вложенный/Пул] {0} [{1}] {2:F2} ГБ",
            ["DirectReadLabel"] = "(прямое чтение)",
            ["ExtractedLabel"] = "(извлечён)",
            ["AboutTitle"] = "О программе",
            ["AboutText"] = "Просмотрщик виртуальных дисков\nВерсия 1.0\n\nПоддерживает форматы VHD/VHDX/VMDK/VDI/QCOW2/RAW\nПоддерживает файловые системы NTFS/FAT\nПоддерживает Пространства хранения Windows (SPACEDB/OSPool)\n\nОрганизация: WinStory 2026\nhttps://wiki.win-story.cn\nКомпиляция: DF4D3110",
            ["LangSelectTitle"] = "Выбор языка",
            ["LangSelectPrompt"] = "Выберите язык интерфейса:",
            ["UnknownLang"] = "Неизвестный код языка, используется zh-cn по умолчанию. Поддерживаются: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
        ["ko-kr"] = new()
        {
            ["AppTitle"] = "가상 디스크 탐색기",
            ["FileMenu"] = "파일(&F)",
            ["OpenDisk"] = "디스크 열기...",
            ["Exit"] = "종료",
            ["LanguageMenu"] = "언어(&L)",
            ["HelpMenu"] = "도움말(&H)",
            ["About"] = "정보",
            ["OpenBtn"] = "열기",
            ["BackBtn"] = "뒤로",
            ["ForwardBtn"] = "앞으로",
            ["UpBtn"] = "위로",
            ["PathLabel"] = "경로:",
            ["ColName"] = "이름",
            ["ColSize"] = "크기",
            ["ColType"] = "유형",
            ["ColModified"] = "수정한 날짜",
            ["Disk"] = "디스크",
            ["Partition"] = "파티션",
            ["RawFs"] = "원시 파일 시스템",
            ["OpenDiskTitle"] = "가상 디스크 파일 선택",
            ["OpenDiskFilter"] = "가상 디스크 파일 (*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd)|*.vhd;*.vhdx;*.vmdk;*.vdi;*.qcow;*.qcow2;*.raw;*.img;*.dd|모든 파일 (*.*)|*.*",
            ["ErrorOpenDisk"] = "디스크를 열 수 없습니다: ",
            ["ErrorOpenPartition"] = "파티션을 열 수 없습니다: ",
            ["ErrorOpenFile"] = "파일을 열 수 없습니다: ",
            ["NoFilesystem"] = "(인식할 수 없는 파일 시스템)",
            ["EmptyFolder"] = "(빈 폴더)",
            ["Folder"] = "폴더",
            ["File"] = "파일",
            ["SPACEDB"] = "Windows 저장 공간 (SPACEDB) - OSPool",
            ["SPACEDBVersion"] = "버전: ",
            ["SPACEDBPoolId"] = "풀 ID: ",
            ["SPACEDBSize"] = "풀 크기: ",
            ["SPACEDBVirtualDisks"] = "가상 디스크",
            ["SPACEDBNote"] = "[참고] SPACEDB는 블록 할당을 사용합니다; 데이터가 비연속적일 수 있습니다. 전체 탐색에는 변환이 필요합니다.",
            ["StoragePool"] = "저장 풀",
            ["Info"] = "정보",
            ["VirtualDisk"] = "가상 디스크",
            ["DoubleClickBrowse"] = "두 번 클릭하여 탐색",
            ["SPACEDBLocationNotFound"] = "가상 디스크 위치를 감지하지 못했습니다.\n\n대체 방법으로 전체 추출을 시도하시겠습니까?",
            ["SPACEDBOpenTitle"] = "SPACEDB 가상 디스크",
            ["SPACEDBOpenPrompt"] = "가상 디스크 '{0}' ({1:F2} GB)을(를) 열겠습니까?\n\n예 = 직접 읽기 (임시 파일 없음, 권장)\n아니요 = 추출 및 변환 (전체 읽기, 디스크 공간 필요)\n취소 = 작업 안 함",
            ["DirectReadFailed"] = "직접 읽기에 실패했습니다. 대체 방법으로 추출을 시도하시겠습니까?",
            ["DirectReadError"] = "직접 읽기 오류: ",
            ["Extracting"] = "가상 디스크 추출 중... ({0}) - 시간이 걸릴 수 있습니다",
            ["ExtractionFailed"] = "가상 디스크 추출에 실패했습니다.",
            ["OpenExtractedFailed"] = "추출된 가상 디스크를 열 수 없습니다.",
            ["OpeningDirect"] = "가상 디스크 열기 중 (직접 읽기)... ({0})",
            ["NestedDiskLabel"] = "[중첩/저장풀] {0} [{1}] {2:F2} GB",
            ["DirectReadLabel"] = "(직접 읽기)",
            ["ExtractedLabel"] = "(추출됨)",
            ["AboutTitle"] = "정보",
            ["AboutText"] = "가상 디스크 탐색기\n버전 1.0\n\nVHD/VHDX/VMDK/VDI/QCOW2/RAW 형식 지원\nNTFS/FAT 파일 시스템 지원\nWindows 저장 공간 (SPACEDB/OSPool) 지원\n\n조직: WinStory 2026\nhttps://wiki.win-story.cn\n컴파일: DF4D3110",
            ["LangSelectTitle"] = "언어 선택",
            ["LangSelectPrompt"] = "인터페이스 언어를 선택하세요:",
            ["UnknownLang"] = "알 수 없는 언어 코드, 기본값 zh-cn 사용. 지원: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
        },
    };

    public static readonly string[] SupportedLanguages = { "zh-cn", "zh-tw", "en-us", "ja-jp", "ru-ru", "ko-kr" };
    public static readonly string[] LanguageNames = { "简体中文", "繁體中文", "English", "日本語", "Русский", "한국어" };

    public static void SetLanguage(string code)
    {
        if (_strings.ContainsKey(code))
            Current = code;
    }

    public static string Get(string key)
    {
        if (_strings.TryGetValue(Current, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings.TryGetValue("en-us", out var en) && en.TryGetValue(key, out var enVal))
            return enVal;
        return key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
