using System.Collections.Generic;

namespace WimExplorer;

public static class Lang
{
    public static string Current { get; private set; } = "zh-cn";

    static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["zh-cn"] = new()
        {
            ["AppTitle"] = "WIM 镜像浏览器",
            ["FileMenu"] = "文件(&F)",
            ["OpenWim"] = "打开 WIM...",
            ["Extract"] = "解压...",
            ["Exit"] = "退出",
            ["LanguageMenu"] = "语言(&L)",
            ["HelpMenu"] = "帮助(&H)",
            ["About"] = "关于",
            ["OpenBtn"] = "打开",
            ["ExtractBtn"] = "解压",
            ["UpBtn"] = "上级",
            ["PathLabel"] = "路径:",
            ["Image"] = "镜像",
            ["ColName"] = "名称",
            ["ColSize"] = "大小",
            ["ColType"] = "类型",
            ["ColModified"] = "修改时间",
            ["Images"] = "镜像列表",
            ["Files"] = "文件",
            ["Index"] = "索引",
            ["Name"] = "名称",
            ["Description"] = "描述",
            ["Size"] = "大小",
            ["Bootable"] = "可启动",
            ["Yes"] = "是",
            ["No"] = "否",
            ["OpenWimTitle"] = "选择 WIM 镜像文件",
            ["OpenWimFilter"] = "WIM 镜像文件 (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|所有文件 (*.*)|*.*",
            ["ErrorOpenWim"] = "打开 WIM 失败: ",
            ["NoImages"] = "(无镜像)",
            ["SelectImage"] = "请选择一个镜像",
            ["Folder"] = "文件夹",
            ["File"] = "文件",
            ["ExtractTitle"] = "解压文件",
            ["ExtractFolderTitle"] = "选择解压目标文件夹",
            ["Extracting"] = "正在解压...",
            ["ExtractComplete"] = "解压完成",
            ["ExtractFailed"] = "解压失败: ",
            ["ConfirmOverwrite"] = "目标文件已存在，是否覆盖？",
            ["AboutText"] = "WIM 镜像浏览器\n版本 1.0\n\n支持 WIM/ESD/SWM 格式\n支持多镜像、分卷、可启动标志\n支持文件和文件夹解压\n\n组织: WinStory 2026\nhttps://wiki.win-story.cn\n编译者: DF4D3110",
            ["AboutTitle"] = "关于",
            ["UnknownLang"] = "未知语言代码，使用默认 zh-cn。支持: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "分卷",
            ["TotalParts"] = "总分卷",
            ["Compression"] = "压缩方式",
            ["Created"] = "创建时间",
            ["Modified"] = "修改时间",
            ["WimInfo"] = "WIM 信息",
            ["ImageInfo"] = "镜像信息",
        },
        ["zh-tw"] = new()
        {
            ["AppTitle"] = "WIM 映像瀏覽器",
            ["FileMenu"] = "檔案(&F)",
            ["OpenWim"] = "開啟 WIM...",
            ["Extract"] = "解壓...",
            ["Exit"] = "退出",
            ["LanguageMenu"] = "語言(&L)",
            ["HelpMenu"] = "說明(&H)",
            ["About"] = "關於",
            ["OpenBtn"] = "開啟",
            ["ExtractBtn"] = "解壓",
            ["UpBtn"] = "上層",
            ["PathLabel"] = "路徑:",
            ["Image"] = "映像",
            ["ColName"] = "名稱",
            ["ColSize"] = "大小",
            ["ColType"] = "類型",
            ["ColModified"] = "修改時間",
            ["Images"] = "映像清單",
            ["Files"] = "檔案",
            ["Index"] = "索引",
            ["Name"] = "名稱",
            ["Description"] = "描述",
            ["Size"] = "大小",
            ["Bootable"] = "可開機",
            ["Yes"] = "是",
            ["No"] = "否",
            ["OpenWimTitle"] = "選取 WIM 映像檔案",
            ["OpenWimFilter"] = "WIM 映像檔案 (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|所有檔案 (*.*)|*.*",
            ["ErrorOpenWim"] = "開啟 WIM 失敗: ",
            ["NoImages"] = "(無映像)",
            ["SelectImage"] = "請選取一個映像",
            ["Folder"] = "資料夾",
            ["File"] = "檔案",
            ["ExtractTitle"] = "解壓檔案",
            ["ExtractFolderTitle"] = "選取解壓目標資料夾",
            ["Extracting"] = "正在解壓...",
            ["ExtractComplete"] = "解壓完成",
            ["ExtractFailed"] = "解壓失敗: ",
            ["ConfirmOverwrite"] = "目標檔案已存在，是否覆蓋？",
            ["AboutText"] = "WIM 映像瀏覽器\n版本 1.0\n\n支援 WIM/ESD/SWM 格式\n支援多映像、分卷、可開機旗標\n支援檔案和資料夾解壓\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\n編譯者: DF4D3110",
            ["AboutTitle"] = "關於",
            ["UnknownLang"] = "未知語言代碼，使用預設 zh-cn。支援: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "分卷",
            ["TotalParts"] = "總分卷",
            ["Compression"] = "壓縮方式",
            ["Created"] = "建立時間",
            ["Modified"] = "修改時間",
            ["WimInfo"] = "WIM 資訊",
            ["ImageInfo"] = "映像資訊",
        },
        ["en-us"] = new()
        {
            ["AppTitle"] = "WIM Image Explorer",
            ["FileMenu"] = "&File",
            ["OpenWim"] = "&Open WIM...",
            ["Extract"] = "&Extract...",
            ["Exit"] = "E&xit",
            ["LanguageMenu"] = "&Language",
            ["HelpMenu"] = "&Help",
            ["About"] = "&About",
            ["OpenBtn"] = "Open",
            ["ExtractBtn"] = "Extract",
            ["UpBtn"] = "Up",
            ["PathLabel"] = "Path:",
            ["Image"] = "Image",
            ["ColName"] = "Name",
            ["ColSize"] = "Size",
            ["ColType"] = "Type",
            ["ColModified"] = "Modified",
            ["Images"] = "Images",
            ["Files"] = "Files",
            ["Index"] = "Index",
            ["Name"] = "Name",
            ["Description"] = "Description",
            ["Size"] = "Size",
            ["Bootable"] = "Bootable",
            ["Yes"] = "Yes",
            ["No"] = "No",
            ["OpenWimTitle"] = "Select WIM Image File",
            ["OpenWimFilter"] = "WIM Image Files (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|All Files (*.*)|*.*",
            ["ErrorOpenWim"] = "Failed to open WIM: ",
            ["NoImages"] = "(no images)",
            ["SelectImage"] = "Please select an image",
            ["Folder"] = "Folder",
            ["File"] = "File",
            ["ExtractTitle"] = "Extract Files",
            ["ExtractFolderTitle"] = "Select Destination Folder",
            ["Extracting"] = "Extracting...",
            ["ExtractComplete"] = "Extraction complete",
            ["ExtractFailed"] = "Extraction failed: ",
            ["ConfirmOverwrite"] = "Destination file already exists. Overwrite?",
            ["AboutText"] = "WIM Image Explorer\nVersion 1.0\n\nSupports WIM/ESD/SWM formats\nSupports multi-image, split volumes, bootable flag\nSupports file and folder extraction\n\nOrganization: WinStory 2026\nhttps://wiki.win-story.cn\nCompiled by: DF4D3110",
            ["AboutTitle"] = "About",
            ["UnknownLang"] = "Unknown language code, using default zh-cn. Supported: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "Part",
            ["TotalParts"] = "Total Parts",
            ["Compression"] = "Compression",
            ["Created"] = "Created",
            ["Modified"] = "Modified",
            ["WimInfo"] = "WIM Info",
            ["ImageInfo"] = "Image Info",
        },
        ["ja-jp"] = new()
        {
            ["AppTitle"] = "WIM イメージブラウザ",
            ["FileMenu"] = "ファイル(&F)",
            ["OpenWim"] = "WIM を開く...",
            ["Extract"] = "展開...",
            ["Exit"] = "終了",
            ["LanguageMenu"] = "言語(&L)",
            ["HelpMenu"] = "ヘルプ(&H)",
            ["About"] = "バージョン情報",
            ["OpenBtn"] = "開く",
            ["ExtractBtn"] = "展開",
            ["UpBtn"] = "上へ",
            ["PathLabel"] = "パス:",
            ["Image"] = "イメージ",
            ["ColName"] = "名前",
            ["ColSize"] = "サイズ",
            ["ColType"] = "種類",
            ["ColModified"] = "更新日時",
            ["Images"] = "イメージ一覧",
            ["Files"] = "ファイル",
            ["Index"] = "インデックス",
            ["Name"] = "名前",
            ["Description"] = "説明",
            ["Size"] = "サイズ",
            ["Bootable"] = "起動可能",
            ["Yes"] = "はい",
            ["No"] = "いいえ",
            ["OpenWimTitle"] = "WIM イメージファイルを選択",
            ["OpenWimFilter"] = "WIM イメージファイル (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|すべてのファイル (*.*)|*.*",
            ["ErrorOpenWim"] = "WIM を開けません: ",
            ["NoImages"] = "(イメージなし)",
            ["SelectImage"] = "イメージを選択してください",
            ["Folder"] = "フォルダ",
            ["File"] = "ファイル",
            ["ExtractTitle"] = "ファイルを展開",
            ["ExtractFolderTitle"] = "展開先フォルダを選択",
            ["Extracting"] = "展開中...",
            ["ExtractComplete"] = "展開完了",
            ["ExtractFailed"] = "展開失敗: ",
            ["ConfirmOverwrite"] = "宛先ファイルが既に存在します。上書きしますか？",
            ["AboutText"] = "WIM イメージブラウザ\nバージョン 1.0\n\nWIM/ESD/SWM 形式をサポート\nマルチイメージ、分割ボリューム、起動可能フラグをサポート\nファイルとフォルダの展開をサポート\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\nコンパイル: DF4D3110",
            ["AboutTitle"] = "バージョン情報",
            ["UnknownLang"] = "不明な言語コード、デフォルト zh-cn を使用。サポート: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "パート",
            ["TotalParts"] = "総パート",
            ["Compression"] = "圧縮方式",
            ["Created"] = "作成日時",
            ["Modified"] = "更新日時",
            ["WimInfo"] = "WIM 情報",
            ["ImageInfo"] = "イメージ情報",
        },
        ["ru-ru"] = new()
        {
            ["AppTitle"] = "Просмотрщик образов WIM",
            ["FileMenu"] = "Файл(&F)",
            ["OpenWim"] = "Открыть WIM...",
            ["Extract"] = "Извлечь...",
            ["Exit"] = "Выход",
            ["LanguageMenu"] = "Язык(&L)",
            ["HelpMenu"] = "Справка(&H)",
            ["About"] = "О программе",
            ["OpenBtn"] = "Открыть",
            ["ExtractBtn"] = "Извлечь",
            ["UpBtn"] = "Вверх",
            ["PathLabel"] = "Путь:",
            ["Image"] = "Образ",
            ["ColName"] = "Имя",
            ["ColSize"] = "Размер",
            ["ColType"] = "Тип",
            ["ColModified"] = "Изменён",
            ["Images"] = "Образы",
            ["Files"] = "Файлы",
            ["Index"] = "Индекс",
            ["Name"] = "Имя",
            ["Description"] = "Описание",
            ["Size"] = "Размер",
            ["Bootable"] = "Загрузочный",
            ["Yes"] = "Да",
            ["No"] = "Нет",
            ["OpenWimTitle"] = "Выберите файл образа WIM",
            ["OpenWimFilter"] = "Файлы образов WIM (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|Все файлы (*.*)|*.*",
            ["ErrorOpenWim"] = "Не удалось открыть WIM: ",
            ["NoImages"] = "(нет образов)",
            ["SelectImage"] = "Пожалуйста, выберите образ",
            ["Folder"] = "Папка",
            ["File"] = "Файл",
            ["ExtractTitle"] = "Извлечь файлы",
            ["ExtractFolderTitle"] = "Выберите папку назначения",
            ["Extracting"] = "Извлечение...",
            ["ExtractComplete"] = "Извлечение завершено",
            ["ExtractFailed"] = "Ошибка извлечения: ",
            ["ConfirmOverwrite"] = "Файл назначения уже существует. Перезаписать?",
            ["AboutText"] = "Просмотрщик образов WIM\nВерсия 1.0\n\nПоддерживает форматы WIM/ESD/SWM\nПоддерживает мульти-образы, разделённые тома, флаг загрузочности\nПоддерживает извлечение файлов и папок\n\nОрганизация: WinStory 2026\nhttps://wiki.win-story.cn\nКомпиляция: DF4D3110",
            ["AboutTitle"] = "О программе",
            ["UnknownLang"] = "Неизвестный код языка, используется zh-cn по умолчанию. Поддерживаются: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "Часть",
            ["TotalParts"] = "Всего частей",
            ["Compression"] = "Сжатие",
            ["Created"] = "Создан",
            ["Modified"] = "Изменён",
            ["WimInfo"] = "Инфо WIM",
            ["ImageInfo"] = "Инфо образа",
        },
        ["ko-kr"] = new()
        {
            ["AppTitle"] = "WIM 이미지 탐색기",
            ["FileMenu"] = "파일(&F)",
            ["OpenWim"] = "WIM 열기...",
            ["Extract"] = "추출...",
            ["Exit"] = "종료",
            ["LanguageMenu"] = "언어(&L)",
            ["HelpMenu"] = "도움말(&H)",
            ["About"] = "정보",
            ["OpenBtn"] = "열기",
            ["ExtractBtn"] = "추출",
            ["UpBtn"] = "위로",
            ["PathLabel"] = "경로:",
            ["Image"] = "이미지",
            ["ColName"] = "이름",
            ["ColSize"] = "크기",
            ["ColType"] = "유형",
            ["ColModified"] = "수정한 날짜",
            ["Images"] = "이미지 목록",
            ["Files"] = "파일",
            ["Index"] = "인덱스",
            ["Name"] = "이름",
            ["Description"] = "설명",
            ["Size"] = "크기",
            ["Bootable"] = "부팅 가능",
            ["Yes"] = "예",
            ["No"] = "아니요",
            ["OpenWimTitle"] = "WIM 이미지 파일 선택",
            ["OpenWimFilter"] = "WIM 이미지 파일 (*.wim;*.esd;*.swm)|*.wim;*.esd;*.swm|모든 파일 (*.*)|*.*",
            ["ErrorOpenWim"] = "WIM을 열 수 없습니다: ",
            ["NoImages"] = "(이미지 없음)",
            ["SelectImage"] = "이미지를 선택하세요",
            ["Folder"] = "폴더",
            ["File"] = "파일",
            ["ExtractTitle"] = "파일 추출",
            ["ExtractFolderTitle"] = "대상 폴더 선택",
            ["Extracting"] = "추출 중...",
            ["ExtractComplete"] = "추출 완료",
            ["ExtractFailed"] = "추출 실패: ",
            ["ConfirmOverwrite"] = "대상 파일이 이미 존재합니다. 덮어쓰시겠습니까?",
            ["AboutText"] = "WIM 이미지 탐색기\n버전 1.0\n\nWIM/ESD/SWM 형식 지원\n멀티 이미지, 분할 볼륨, 부팅 가능 플래그 지원\n파일 및 폴더 추출 지원\n\n조직: WinStory 2026\nhttps://wiki.win-story.cn\n컴파일: DF4D3110",
            ["AboutTitle"] = "정보",
            ["UnknownLang"] = "알 수 없는 언어 코드, 기본값 zh-cn 사용. 지원: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["PartNumber"] = "파트",
            ["TotalParts"] = "총 파트",
            ["Compression"] = "압축 방식",
            ["Created"] = "만든 날짜",
            ["Modified"] = "수정한 날짜",
            ["WimInfo"] = "WIM 정보",
            ["ImageInfo"] = "이미지 정보",
        },
    };

    public static readonly string[] SupportedLanguages = { "zh-cn", "zh-tw", "en-us", "ja-jp", "ru-ru", "ko-kr" };
    public static readonly string[] LanguageNames = { "简体中文", "繁體中文", "English", "日本語", "Русский", "한국어" };

    public static void SetLanguage(string code)
    {
        if (_strings.ContainsKey(code))
            Current = code;
    }

    public static string Get(string key)
    {
        if (_strings.TryGetValue(Current, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings.TryGetValue("en-us", out var en) && en.TryGetValue(key, out var enVal))
            return enVal;
        return key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
