<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>wimexplorer</AssemblyName>
    <RootNamespace>WimExplorer</RootNamespace>
    <Version>1.0.4</Version>
    <Company>WinStory 2026</Company>
    <Product>WSK Tools</Product>
    <Copyright>Copyright (C) 2026 WinStory</Copyright>
    <Description>wimexplorer - WIM Image Explorer</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Core" Version="1.0.51" />
    <PackageReference Include="LTRData.DiscUtils.Wim" Version="1.0.51" />
  </ItemGroup>
</Project>
