
#pragma once

#define IDS_APP_TITLE        100
#define IDS_LBL_FFU          101
#define IDS_BTN_BROWSE       102
#define IDS_LBL_DISK         103
#define IDS_BTN_REFRESH      104
#define IDS_BTN_START        105
#define IDS_LBL_OUTPUT       106
#define IDS_STATUS_READY     107
#define IDS_MSG_SEL_FFU      108
#define IDS_MSG_FFU_NOTEXIST 109
#define IDS_MSG_SEL_DISK     110
#define IDS_MSG_INVALID_DISK 111
#define IDS_MSG_WARN_TITLE   112
#define IDS_MSG_WARN_BODY1   113
#define IDS_MSG_WARN_BODY2   114
#define IDS_MSG_WARN_BODY3   115
#define IDS_MSG_PERM_TITLE   116
#define IDS_MSG_PERM_BODY    117
#define IDS_STATUS_RUNNING   118
#define IDS_OUT_START        119
#define IDS_OUT_FFU          120
#define IDS_OUT_DISK         121
#define IDS_OUT_THREAD_FAIL  122
#define IDS_MSG_ERROR        123
#define IDS_MSG_PROMPT       124
#define IDS_OUT_HEADER       125
#define IDS_OUT_ARCH         126
#define IDS_OUT_PERM_YES     127
#define IDS_OUT_PERM_NO      128
#define IDS_OUT_DETECT       129
#define IDS_OUT_DISM_VER     130
#define IDS_OUT_FFU_YES      131
#define IDS_OUT_FFU_NO       132
#define IDS_OUT_FFU_TIP      133
#define IDS_STATUS_FFU_OK    134
#define IDS_STATUS_FFU_NO    135
#define IDS_OUT_DISK_COUNT   136
#define IDS_OUT_REFRESH      137
#define IDS_STATUS_PROGRESS  138
#define IDS_OUT_SUCCESS      139
#define IDS_STATUS_SUCCESS    140
#define IDS_MSG_SUCCESS      141
#define IDS_MSG_DONE         142
#define IDS_OUT_FAIL         143
#define IDS_OUT_EXITCODE     144
#define IDS_OUT_ERRMSG       145
#define IDS_STATUS_FAIL      146
#define IDS_MSG_FAIL         147
#define IDS_MSG_FAILTITLE    148
#define IDS_NO_DISK          149
#define IDS_SIZE_UNKNOWN     150
#define IDS_NEED_ADMIN       151
#define IDS_MENU_LANG        152
#define IDS_MENU_SWITCH      153
#define IDS_MENU_HELP        154
#define IDS_MENU_ABOUT       155
#define IDS_FFU_FILTER       156
#define IDS_FFU_ALLFILES     157
#define IDS_FFU_DIALOG       158
