using System.Collections.Generic;

namespace FFUView;

public static class Lang
{
    public static string Current { get; private set; } = "zh-cn";

    static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["zh-cn"] = new()
        {
            ["Usage"] = "用法: ffuinfo <ffu文件路径> [-l 语言代码]",
            ["UsageDesc"] = "使用 Img2Ffu 分析 FFU 文件结构和分区。",
            ["LangOption"] = "  -l, -language <code>  指定输出语言 (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr)，默认 zh-cn",
            ["FileNotFound"] = "文件未找到: ",
            ["UnknownLang"] = "未知语言代码，使用默认 zh-cn。支持: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "FFU 文件分析: ",
            ["FileSize"] = "文件大小: ",
            ["Header"] = "--- 文件头 ---",
            ["Signature"] = "签名: ",
            ["HeaderSize"] = "头部大小: ",
            ["CertSize"] = "证书/Blob 大小: ",
            ["TableSize"] = "存储表大小: ",
            ["TotalHeader"] = "总头部: ",
            ["DataOffset"] = "数据偏移: ",
            ["Stores"] = "--- 存储: ",
            ["Store"] = "存储 ",
            ["Length"] = "长度: ",
            ["SectorSize"] = "扇区大小: ",
            ["DevicePath"] = "设备路径: ",
            ["Partitions"] = "分区: ",
            ["Partition"] = "分区",
            ["Name"] = "名称",
            ["Type"] = "类型",
            ["StartLBA"] = "起始 LBA",
            ["EndLBA"] = "结束 LBA",
            ["Size"] = "大小",
            ["FileSystem"] = "文件系统",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => 检测到 OSPool 分区!",
            ["OSPoolSig"] = "  SPACEDB 签名: ",
            ["OSPoolVirtualDisks"] = "  虚拟磁盘: ",
            ["VirtualDisk"] = "虚拟磁盘",
            ["NoPartitions"] = "  (无分区表)",
            ["ParseError"] = "解析错误: ",
            ["Error"] = "错误: ",
            ["InnerError"] = "内部错误: ",
        },
        ["zh-tw"] = new()
        {
            ["Usage"] = "用法: ffuinfo <ffu檔案路徑> [-l 語言代碼]",
            ["UsageDesc"] = "使用 Img2Ffu 分析 FFU 檔案結構和分割區。",
            ["LangOption"] = "  -l, -language <code>  指定輸出語言 (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr)，預設 zh-cn",
            ["FileNotFound"] = "檔案未找到: ",
            ["UnknownLang"] = "未知語言代碼，使用預設 zh-cn。支援: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "FFU 檔案分析: ",
            ["FileSize"] = "檔案大小: ",
            ["Header"] = "--- 檔案頭 ---",
            ["Signature"] = "簽名: ",
            ["HeaderSize"] = "頭部大小: ",
            ["CertSize"] = "憑證/Blob 大小: ",
            ["TableSize"] = "儲存表大小: ",
            ["TotalHeader"] = "總頭部: ",
            ["DataOffset"] = "資料偏移: ",
            ["Stores"] = "--- 儲存: ",
            ["Store"] = "儲存 ",
            ["Length"] = "長度: ",
            ["SectorSize"] = "磁區大小: ",
            ["DevicePath"] = "裝置路徑: ",
            ["Partitions"] = "分割區: ",
            ["Partition"] = "分割區",
            ["Name"] = "名稱",
            ["Type"] = "類型",
            ["StartLBA"] = "起始 LBA",
            ["EndLBA"] = "結束 LBA",
            ["Size"] = "大小",
            ["FileSystem"] = "檔案系統",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => 偵測到 OSPool 分割區!",
            ["OSPoolSig"] = "  SPACEDB 簽名: ",
            ["OSPoolVirtualDisks"] = "  虛擬磁碟: ",
            ["VirtualDisk"] = "虛擬磁碟",
            ["NoPartitions"] = "  (無分割區表)",
            ["ParseError"] = "解析錯誤: ",
            ["Error"] = "錯誤: ",
            ["InnerError"] = "內部錯誤: ",
        },
        ["en-us"] = new()
        {
            ["Usage"] = "Usage: ffuinfo <ffu_file_path> [-l language_code]",
            ["UsageDesc"] = "Analyzes FFU file structure and partitions using Img2Ffu.",
            ["LangOption"] = "  -l, -language <code>  Output language (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr), default zh-cn",
            ["FileNotFound"] = "File not found: ",
            ["UnknownLang"] = "Unknown language code, using default zh-cn. Supported: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "FFU File Analysis: ",
            ["FileSize"] = "File size: ",
            ["Header"] = "--- Header ---",
            ["Signature"] = "Signature: ",
            ["HeaderSize"] = "Header size: ",
            ["CertSize"] = "Cert/Blob size: ",
            ["TableSize"] = "Store table size: ",
            ["TotalHeader"] = "Total header: ",
            ["DataOffset"] = "Data offset: ",
            ["Stores"] = "--- Stores: ",
            ["Store"] = "Store ",
            ["Length"] = "Length: ",
            ["SectorSize"] = "Sector size: ",
            ["DevicePath"] = "Device path: ",
            ["Partitions"] = "Partitions: ",
            ["Partition"] = "Partition",
            ["Name"] = "Name",
            ["Type"] = "Type",
            ["StartLBA"] = "Start LBA",
            ["EndLBA"] = "End LBA",
            ["Size"] = "Size",
            ["FileSystem"] = "File system",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => OSPool partition detected!",
            ["OSPoolSig"] = "  SPACEDB signature: ",
            ["OSPoolVirtualDisks"] = "  Virtual disks: ",
            ["VirtualDisk"] = "Virtual disk",
            ["NoPartitions"] = "  (no partition table)",
            ["ParseError"] = "Parse error: ",
            ["Error"] = "Error: ",
            ["InnerError"] = "Inner error: ",
        },
        ["ja-jp"] = new()
        {
            ["Usage"] = "使い方: ffuinfo <ffuファイルパス> [-l 言語コード]",
            ["UsageDesc"] = "Img2Ffu を使用して FFU ファイル構造とパーティションを分析します。",
            ["LangOption"] = "  -l, -language <code>  出力言語 (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr)、デフォルト zh-cn",
            ["FileNotFound"] = "ファイルが見つかりません: ",
            ["UnknownLang"] = "不明な言語コード、デフォルト zh-cn を使用。対応: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "FFU ファイル分析: ",
            ["FileSize"] = "ファイルサイズ: ",
            ["Header"] = "--- ヘッダー ---",
            ["Signature"] = "シグネチャ: ",
            ["HeaderSize"] = "ヘッダーサイズ: ",
            ["CertSize"] = "証明書/Blob サイズ: ",
            ["TableSize"] = "ストアテーブルサイズ: ",
            ["TotalHeader"] = "合計ヘッダー: ",
            ["DataOffset"] = "データオフセット: ",
            ["Stores"] = "--- ストア: ",
            ["Store"] = "ストア ",
            ["Length"] = "長さ: ",
            ["SectorSize"] = "セクターサイズ: ",
            ["DevicePath"] = "デバイスパス: ",
            ["Partitions"] = "パーティション: ",
            ["Partition"] = "パーティション",
            ["Name"] = "名前",
            ["Type"] = "タイプ",
            ["StartLBA"] = "開始 LBA",
            ["EndLBA"] = "終了 LBA",
            ["Size"] = "サイズ",
            ["FileSystem"] = "ファイルシステム",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => OSPool パーティションを検出!",
            ["OSPoolSig"] = "  SPACEDB シグネチャ: ",
            ["OSPoolVirtualDisks"] = "  仮想ディスク: ",
            ["VirtualDisk"] = "仮想ディスク",
            ["NoPartitions"] = "  (パーティションテーブルなし)",
            ["ParseError"] = "解析エラー: ",
            ["Error"] = "エラー: ",
            ["InnerError"] = "内部エラー: ",
        },
        ["ru-ru"] = new()
        {
            ["Usage"] = "Использование: ffuinfo <путь_к_ffu> [-l код_языка]",
            ["UsageDesc"] = "Анализ структуры FFU и разделов с помощью Img2Ffu.",
            ["LangOption"] = "  -l, -language <code>  Язык вывода (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr), по умолчанию zh-cn",
            ["FileNotFound"] = "Файл не найден: ",
            ["UnknownLang"] = "Неизвестный код языка, используется zh-cn. Поддерживаются: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "Анализ FFU: ",
            ["FileSize"] = "Размер файла: ",
            ["Header"] = "--- Заголовок ---",
            ["Signature"] = "Сигнатура: ",
            ["HeaderSize"] = "Размер заголовка: ",
            ["CertSize"] = "Размер сертификата/Blob: ",
            ["TableSize"] = "Размер таблицы хранилищ: ",
            ["TotalHeader"] = "Общий заголовок: ",
            ["DataOffset"] = "Смещение данных: ",
            ["Stores"] = "--- Хранилища: ",
            ["Store"] = "Хранилище ",
            ["Length"] = "Длина: ",
            ["SectorSize"] = "Размер сектора: ",
            ["DevicePath"] = "Путь устройства: ",
            ["Partitions"] = "Разделы: ",
            ["Partition"] = "Раздел",
            ["Name"] = "Имя",
            ["Type"] = "Тип",
            ["StartLBA"] = "Начальный LBA",
            ["EndLBA"] = "Конечный LBA",
            ["Size"] = "Размер",
            ["FileSystem"] = "Файловая система",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => Обнаружен раздел OSPool!",
            ["OSPoolSig"] = "  Сигнатура SPACEDB: ",
            ["OSPoolVirtualDisks"] = "  Виртуальные диски: ",
            ["VirtualDisk"] = "Виртуальный диск",
            ["NoPartitions"] = "  (нет таблицы разделов)",
            ["ParseError"] = "Ошибка анализа: ",
            ["Error"] = "Ошибка: ",
            ["InnerError"] = "Внутренняя ошибка: ",
        },
        ["ko-kr"] = new()
        {
            ["Usage"] = "사용법: ffuinfo <ffu_파일경로> [-l 언어코드]",
            ["UsageDesc"] = "Img2Ffu를 사용하여 FFU 파일 구조와 파티션을 분석합니다.",
            ["LangOption"] = "  -l, -language <code>  출력 언어 (zh-cn/zh-tw/en-us/ja-jp/ru-ru/ko-kr), 기본값 zh-cn",
            ["FileNotFound"] = "파일을 찾을 수 없음: ",
            ["UnknownLang"] = "알 수 없는 언어 코드, 기본값 zh-cn 사용. 지원: zh-cn zh-tw en-us ja-jp ru-ru ko-kr",
            ["AnalysisTitle"] = "FFU 파일 분석: ",
            ["FileSize"] = "파일 크기: ",
            ["Header"] = "--- 헤더 ---",
            ["Signature"] = "서명: ",
            ["HeaderSize"] = "헤더 크기: ",
            ["CertSize"] = "인증서/Blob 크기: ",
            ["TableSize"] = "스토어 테이블 크기: ",
            ["TotalHeader"] = "총 헤더: ",
            ["DataOffset"] = "데이터 오프셋: ",
            ["Stores"] = "--- 스토어: ",
            ["Store"] = "스토어 ",
            ["Length"] = "길이: ",
            ["SectorSize"] = "섹터 크기: ",
            ["DevicePath"] = "장치 경로: ",
            ["Partitions"] = "파티션: ",
            ["Partition"] = "파티션",
            ["Name"] = "이름",
            ["Type"] = "유형",
            ["StartLBA"] = "시작 LBA",
            ["EndLBA"] = "끝 LBA",
            ["Size"] = "크기",
            ["FileSystem"] = "파일 시스템",
            ["OSPool"] = " [OSPool]",
            ["OSPoolDetected"] = "  => OSPool 파티션 감지!",
            ["OSPoolSig"] = "  SPACEDB 서명: ",
            ["OSPoolVirtualDisks"] = "  가상 디스크: ",
            ["VirtualDisk"] = "가상 디스크",
            ["NoPartitions"] = "  (파티션 테이블 없음)",
            ["ParseError"] = "분석 오류: ",
            ["Error"] = "오류: ",
            ["InnerError"] = "내부 오류: ",
        },
    };

    public static void SetLanguage(string code)
    {
        if (_strings.ContainsKey(code))
            Current = code;
    }

    public static string Get(string key)
    {
        if (_strings.TryGetValue(Current, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings.TryGetValue("en-us", out var en) && en.TryGetValue(key, out var enVal))
            return enVal;
        return key;
    }
}
