using System.Collections.Generic;

namespace WcosStageTool;

internal static class Lang
{
    public static readonly string[] SupportedLanguages = { "zh-cn", "zh-tw", "en-us", "ja-jp", "ru-ru", "ko-kr" };
    private static string _current = "zh-cn";

    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["zh-cn"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "WCOS 构建",
            ["TabPatch"] = "驱动注入",
            ["TabUpdate"] = "CAB 注入",
            ["TabBcd"] = "BCD 编辑",
            ["ToolPath"] = "工具路径:",
            ["Browse"] = "浏览...",
            ["OutputDir"] = "输出目录:",
            ["FfuName"] = "FFU 文件名:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "MSPackage 根目录:",
            ["CpuType"] = "CPU 类型:",
            ["Run"] = "开始执行",
            ["FfuPath"] = "FFU 路径:",
            ["DriverDir"] = "驱动目录:",
            ["VhdPath"] = "VHD 路径:",
            ["CabDir"] = "CAB 目录:",
            ["BcdPath"] = "BCD 文件:",
            ["Debug"] = "启用调试",
            ["Serial"] = "串口调试",
            ["DebugPort"] = "调试端口 COM1",
            ["BaudRate"] = "波特率 115200",
            ["TestSign"] = "测试签名",
            ["NoIntegrity"] = "禁用完整性检查",
            ["Output"] = "输出:",
            ["Ready"] = "就绪",
            ["Running"] = "执行中...",
            ["Done"] = "完成",
            ["Failed"] = "失败",
            ["SelectTool"] = "请选择工具路径",
            ["SelectOutput"] = "请填写输出目录",
            ["SelectXml"] = "请选择 OEMInput XML",
            ["SelectPkg"] = "请选择 MSPackage 根目录",
            ["SelectFfu"] = "请选择 FFU 路径",
            ["SelectDriver"] = "请选择驱动目录",
            ["SelectCpu"] = "请选择 CPU 类型",
            ["SelectVhd"] = "请选择 VHD 路径",
            ["SelectCab"] = "请选择 CAB 目录",
            ["SelectBcd"] = "请选择 BCD 文件",
            ["SelectOption"] = "请至少勾选一个选项",
            ["DirNotEmpty"] = "输出目录非空，请选择其他目录或清空后继续",
            ["CreateDir"] = "输出目录不存在，是否创建?",
            ["Language"] = "语言",
            ["About"] = "关于",
            ["File"] = "文件",
            ["Exit"] = "退出",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nWCOS 构建与镜像后期处理工具\n\n组织: WinStory 2026\nhttps://wiki.win-story.cn\n编译者: DF4D3110",
            ["NavTitle"] = "功能选择",
            ["TestWarning"] = "⚠ 测试版本 — 部分功能可能存在无法正常工作",
            ["OK"] = "确定",
        },
        ["zh-tw"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "WCOS 建置",
            ["TabPatch"] = "驅動注入",
            ["TabUpdate"] = "CAB 注入",
            ["TabBcd"] = "BCD 編輯",
            ["ToolPath"] = "工具路徑:",
            ["Browse"] = "瀏覽...",
            ["OutputDir"] = "輸出目錄:",
            ["FfuName"] = "FFU 檔名:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "MSPackage 根目錄:",
            ["CpuType"] = "CPU 類型:",
            ["Run"] = "開始執行",
            ["FfuPath"] = "FFU 路徑:",
            ["DriverDir"] = "驅動目錄:",
            ["VhdPath"] = "VHD 路徑:",
            ["CabDir"] = "CAB 目錄:",
            ["BcdPath"] = "BCD 檔案:",
            ["Debug"] = "啟用除錯",
            ["Serial"] = "序列埠除錯",
            ["DebugPort"] = "除錯連接埠 COM1",
            ["BaudRate"] = "鮑率 115200",
            ["TestSign"] = "測試簽章",
            ["NoIntegrity"] = "停用完整性檢查",
            ["Output"] = "輸出:",
            ["Ready"] = "就緒",
            ["Running"] = "執行中...",
            ["Done"] = "完成",
            ["Failed"] = "失敗",
            ["SelectTool"] = "請選擇工具路徑",
            ["SelectOutput"] = "請填寫輸出目錄",
            ["SelectXml"] = "請選擇 OEMInput XML",
            ["SelectPkg"] = "請選擇 MSPackage 根目錄",
            ["SelectFfu"] = "請選擇 FFU 路徑",
            ["SelectDriver"] = "請選擇驅動目錄",
            ["SelectCpu"] = "請選擇 CPU 類型",
            ["SelectVhd"] = "請選擇 VHD 路徑",
            ["SelectCab"] = "請選擇 CAB 目錄",
            ["SelectBcd"] = "請選擇 BCD 檔案",
            ["SelectOption"] = "請至少勾選一個選項",
            ["DirNotEmpty"] = "輸出目錄非空，請選擇其他目錄或清空後繼續",
            ["CreateDir"] = "輸出目錄不存在，是否建立?",
            ["Language"] = "語言",
            ["About"] = "關於",
            ["File"] = "檔案",
            ["Exit"] = "結束",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nWCOS 建置與鏡像後期處理工具\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\n編譯者: DF4D3110",
            ["NavTitle"] = "功能選擇",
            ["TestWarning"] = "⚠ 測試版本 — 部分功能可能存在無法正常工作",
            ["OK"] = "確定",
        },
        ["en-us"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "WCOS Build",
            ["TabPatch"] = "Driver Inject",
            ["TabUpdate"] = "CAB Inject",
            ["TabBcd"] = "BCD Edit",
            ["ToolPath"] = "Tool Path:",
            ["Browse"] = "Browse...",
            ["OutputDir"] = "Output Dir:",
            ["FfuName"] = "FFU Name:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "MSPackage Root:",
            ["CpuType"] = "CPU Type:",
            ["Run"] = "Run",
            ["FfuPath"] = "FFU Path:",
            ["DriverDir"] = "Driver Dir:",
            ["VhdPath"] = "VHD Path:",
            ["CabDir"] = "CAB Dir:",
            ["BcdPath"] = "BCD File:",
            ["Debug"] = "Enable Debug",
            ["Serial"] = "Serial Debug",
            ["DebugPort"] = "Debug Port COM1",
            ["BaudRate"] = "Baud Rate 115200",
            ["TestSign"] = "Test Signing",
            ["NoIntegrity"] = "Disable Integrity Check",
            ["Output"] = "Output:",
            ["Ready"] = "Ready",
            ["Running"] = "Running...",
            ["Done"] = "Done",
            ["Failed"] = "Failed",
            ["SelectTool"] = "Please select tool path",
            ["SelectOutput"] = "Please fill output directory",
            ["SelectXml"] = "Please select OEMInput XML",
            ["SelectPkg"] = "Please select MSPackage root",
            ["SelectFfu"] = "Please select FFU path",
            ["SelectDriver"] = "Please select driver directory",
            ["SelectCpu"] = "Please select CPU type",
            ["SelectVhd"] = "Please select VHD path",
            ["SelectCab"] = "Please select CAB directory",
            ["SelectBcd"] = "Please select BCD file",
            ["SelectOption"] = "Please check at least one option",
            ["DirNotEmpty"] = "Output directory is not empty, please select another or clear it",
            ["CreateDir"] = "Output directory does not exist, create it?",
            ["Language"] = "Language",
            ["About"] = "About",
            ["File"] = "File",
            ["Exit"] = "Exit",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nWCOS build and image post-processing tool\n\nOrg: WinStory 2026\nhttps://wiki.win-story.cn\nCompiled by DF4D3110",
            ["NavTitle"] = "Functions",
            ["TestWarning"] = "⚠ Preview Build - Some features may not work properly",
            ["OK"] = "OK",
        },
        ["ja-jp"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "WCOS ビルド",
            ["TabPatch"] = "ドライバー注入",
            ["TabUpdate"] = "CAB 注入",
            ["TabBcd"] = "BCD 編集",
            ["ToolPath"] = "ツールパス:",
            ["Browse"] = "参照...",
            ["OutputDir"] = "出力ディレクトリ:",
            ["FfuName"] = "FFU ファイル名:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "MSPackage ルート:",
            ["CpuType"] = "CPU タイプ:",
            ["Run"] = "実行開始",
            ["FfuPath"] = "FFU パス:",
            ["DriverDir"] = "ドライバーディレクトリ:",
            ["VhdPath"] = "VHD パス:",
            ["CabDir"] = "CAB ディレクトリ:",
            ["BcdPath"] = "BCD ファイル:",
            ["Debug"] = "デバッグ有効",
            ["Serial"] = "シリアルデバッグ",
            ["DebugPort"] = "デバッグポート COM1",
            ["BaudRate"] = "ボーレート 115200",
            ["TestSign"] = "テスト署名",
            ["NoIntegrity"] = "整合性チェック無効",
            ["Output"] = "出力:",
            ["Ready"] = "準備完了",
            ["Running"] = "実行中...",
            ["Done"] = "完了",
            ["Failed"] = "失敗",
            ["SelectTool"] = "ツールパスを選択してください",
            ["SelectOutput"] = "出力ディレクトリを入力してください",
            ["SelectXml"] = "OEMInput XML を選択してください",
            ["SelectPkg"] = "MSPackage ルートを選択してください",
            ["SelectFfu"] = "FFU パスを選択してください",
            ["SelectDriver"] = "ドライバーディレクトリを選択してください",
            ["SelectCpu"] = "CPU タイプを選択してください",
            ["SelectVhd"] = "VHD パスを選択してください",
            ["SelectCab"] = "CAB ディレクトリを選択してください",
            ["SelectBcd"] = "BCD ファイルを選択してください",
            ["SelectOption"] = "少なくとも1つのオプションをチェックしてください",
            ["DirNotEmpty"] = "出力ディレクトリが空ではありません。別のディレクトリを選択するか空にしてください",
            ["CreateDir"] = "出力ディレクトリが存在しません。作成しますか?",
            ["Language"] = "言語",
            ["About"] = "バージョン情報",
            ["File"] = "ファイル",
            ["Exit"] = "終了",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nWCOS ビルドとイメージ後処理ツール\n\n組織: WinStory 2026\nhttps://wiki.win-story.cn\nコンパイル: DF4D3110",
            ["NavTitle"] = "機能選択",
            ["TestWarning"] = "⚠ プレビュー版 — 一部の機能が正常に動作しない場合があります",
            ["OK"] = "OK",
        },
        ["ru-ru"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "Сборка WCOS",
            ["TabPatch"] = "Ввод драйверов",
            ["TabUpdate"] = "Ввод CAB",
            ["TabBcd"] = "Редактор BCD",
            ["ToolPath"] = "Путь к инструменту:",
            ["Browse"] = "Обзор...",
            ["OutputDir"] = "Выходной каталог:",
            ["FfuName"] = "Имя FFU:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "Корень MSPackage:",
            ["CpuType"] = "Тип CPU:",
            ["Run"] = "Запуск",
            ["FfuPath"] = "Путь FFU:",
            ["DriverDir"] = "Каталог драйверов:",
            ["VhdPath"] = "Путь VHD:",
            ["CabDir"] = "Каталог CAB:",
            ["BcdPath"] = "Файл BCD:",
            ["Debug"] = "Включить отладку",
            ["Serial"] = "Последовательная отладка",
            ["DebugPort"] = "Порт отладки COM1",
            ["BaudRate"] = "Скорость 115200",
            ["TestSign"] = "Тестовая подпись",
            ["NoIntegrity"] = "Отключить проверку целостности",
            ["Output"] = "Вывод:",
            ["Ready"] = "Готово",
            ["Running"] = "Выполняется...",
            ["Done"] = "Завершено",
            ["Failed"] = "Ошибка",
            ["SelectTool"] = "Выберите путь к инструменту",
            ["SelectOutput"] = "Укажите выходной каталог",
            ["SelectXml"] = "Выберите OEMInput XML",
            ["SelectPkg"] = "Выберите корень MSPackage",
            ["SelectFfu"] = "Выберите путь FFU",
            ["SelectDriver"] = "Выберите каталог драйверов",
            ["SelectCpu"] = "Выберите тип CPU",
            ["SelectVhd"] = "Выберите путь VHD",
            ["SelectCab"] = "Выберите каталог CAB",
            ["SelectBcd"] = "Выберите файл BCD",
            ["SelectOption"] = "Отметьте хотя бы один параметр",
            ["DirNotEmpty"] = "Выходной каталог не пуст, выберите другой или очистите",
            ["CreateDir"] = "Выходной каталог не существует, создать?",
            ["Language"] = "Язык",
            ["About"] = "О программе",
            ["File"] = "Файл",
            ["Exit"] = "Выход",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nИнструмент сборки WCOS и постобработки образов\n\nОрганизация: WinStory 2026\nhttps://wiki.win-story.cn\nКомпилятор: DF4D3110",
            ["NavTitle"] = "Функции",
            ["TestWarning"] = "⚠ Предварительная версия — некоторые функции могут работать неправильно",
            ["OK"] = "ОК",
        },
        ["ko-kr"] = new()
        {
            ["Title"] = "WCOS Stage Tool",
            ["TabBuild"] = "WCOS 빌드",
            ["TabPatch"] = "드라이버 주입",
            ["TabUpdate"] = "CAB 주입",
            ["TabBcd"] = "BCD 편집",
            ["ToolPath"] = "도구 경로:",
            ["Browse"] = "찾아보기...",
            ["OutputDir"] = "출력 디렉토리:",
            ["FfuName"] = "FFU 파일명:",
            ["XmlPath"] = "OEMInput XML:",
            ["PkgDir"] = "MSPackage 루트:",
            ["CpuType"] = "CPU 유형:",
            ["Run"] = "실행",
            ["FfuPath"] = "FFU 경로:",
            ["DriverDir"] = "드라이버 디렉토리:",
            ["VhdPath"] = "VHD 경로:",
            ["CabDir"] = "CAB 디렉토리:",
            ["BcdPath"] = "BCD 파일:",
            ["Debug"] = "디버깅 활성화",
            ["Serial"] = "시리얼 디버깅",
            ["DebugPort"] = "디버그 포트 COM1",
            ["BaudRate"] = "전송속도 115200",
            ["TestSign"] = "테스트 서명",
            ["NoIntegrity"] = "무결성 검사 비활성화",
            ["Output"] = "출력:",
            ["Ready"] = "준비",
            ["Running"] = "실행 중...",
            ["Done"] = "완료",
            ["Failed"] = "실패",
            ["SelectTool"] = "도구 경로를 선택하세요",
            ["SelectOutput"] = "출력 디렉토리를 입력하세요",
            ["SelectXml"] = "OEMInput XML을 선택하세요",
            ["SelectPkg"] = "MSPackage 루트를 선택하세요",
            ["SelectFfu"] = "FFU 경로를 선택하세요",
            ["SelectDriver"] = "드라이버 디렉토리를 선택하세요",
            ["SelectCpu"] = "CPU 유형을 선택하세요",
            ["SelectVhd"] = "VHD 경로를 선택하세요",
            ["SelectCab"] = "CAB 디렉토리를 선택하세요",
            ["SelectBcd"] = "BCD 파일을 선택하세요",
            ["SelectOption"] = "최소 하나의 옵션을 체크하세요",
            ["DirNotEmpty"] = "출력 디렉토리가 비어있지 않습니다. 다른 디렉토리를 선택하거나 비우세요",
            ["CreateDir"] = "출력 디렉토리가 존재하지 않습니다. 생성하시겠습니까?",
            ["Language"] = "언어",
            ["About"] = "정보",
            ["File"] = "파일",
            ["Exit"] = "종료",
            ["AboutText"] = "WCOS Stage Tool\nWSK Tools v1.0.3 Preview Build 260825\n\nWCOS 빌드 및 이미지 후처리 도구\n\n조직: WinStory 2026\nhttps://wiki.win-story.cn\n컴파일: DF4D3110",
            ["NavTitle"] = "기능 선택",
            ["TestWarning"] = "⚠ 미리보기 버전 — 일부 기능이 제대로 작동하지 않을 수 있습니다",
            ["OK"] = "확인",
        },
    };

    public static string Get(string key)
    {
        if (_strings.TryGetValue(_current, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings.TryGetValue("en-us", out var enDict) && enDict.TryGetValue(key, out var enVal))
            return enVal;
        return key;
    }

    public static void SetLanguage(string lang)
    {
        lang = lang.ToLower();
        if (System.Array.IndexOf(SupportedLanguages, lang) >= 0)
            _current = lang;
    }

    public static string Current => _current;
}
