
#pragma once

#define IDS_APP_TITLE        100
#define IDS_TAB_BUILD        101
#define IDS_TAB_PATCH        102
#define IDS_TAB_UPDATE       103
#define IDS_TAB_BCD          104
#define IDS_BTN_START        105
#define IDS_BTN_BROWSE       106
#define IDS_BTN_SELECT       107
#define IDS_LBL_IMGGEN       108
#define IDS_LBL_OUTDIR       109
#define IDS_LBL_FFUNAME      110
#define IDS_LBL_XML          111
#define IDS_LBL_PKG          112
#define IDS_LBL_CPU          113
#define IDS_LBL_IMAGEAPP     114
#define IDS_LBL_FFU          115
#define IDS_LBL_DRIVER       116
#define IDS_LBL_UPDATEAPP    117
#define IDS_LBL_VHD          118
#define IDS_LBL_CAB          119
#define IDS_LBL_BCD          120
#define IDS_CHK_DEBUG        121
#define IDS_CHK_SERIAL       122
#define IDS_CHK_PORT         123
#define IDS_CHK_BAUD         124
#define IDS_CHK_TESTSIGN     125
#define IDS_CHK_NOINT        126
#define IDS_STATUS_READY     127
#define IDS_STATUS_RUNNING   128
#define IDS_STATUS_SUCCESS   129
#define IDS_STATUS_FAIL      130
#define IDS_MSG_SEL_IMGGEN   131
#define IDS_MSG_FILL_BUILD   132
#define IDS_MSG_SEL_IMAGEAPP 133
#define IDS_MSG_FILL_PATCH   134
#define IDS_MSG_SEL_UPDATE   135
#define IDS_MSG_FILL_UPDATE  136
#define IDS_MSG_SEL_BCD      137
#define IDS_MSG_CHECK_BCD    138
#define IDS_MSG_DIR_CREATE   139
#define IDS_MSG_DIR_NONEMPTY 140
#define IDS_MSG_SAVE_FFU     141
#define IDS_MSG_NO_LANG      142
#define IDS_MENU_LANG        143
#define IDS_MENU_SWITCH      144
#define IDS_MENU_HELP        153
#define IDS_MENU_ABOUT       154
#define IDS_OUT_SUCCESS      145
#define IDS_OUT_FAIL         146
#define IDS_MSG_AUTODETECT   147
#define IDS_MSG_NO_TOOL      148
#define IDS_DLG_LANG_TITLE   149
#define IDS_DLG_LANG_PROMPT  150
#define IDS_BTN_OK           151
#define IDS_BTN_CANCEL       152
